### ISSUE TITLE
Cannot type space in editor

### ISSUE THREAD

**Issue by lingxiaoyang** [DDMAL/meix.js#60] opened 2015-03-05 19:15 UTC
The editor doesn't insert a space when pressing space bar. Copying and pasting a space works.

**Comment by ahwitz** [comment] 2015-05-20 10:11
@lingxiaoyang / @ribu - can either of you verify this was fixed and we just didn't close the issue? I'm pretty sure this was what I solved a while ago but I'm not sure.

**Comment by ahankinson** [comment] 2015-05-20 10:17
Seems to me that this one's pretty easy to check. I can confirm that pressing the space bar inserts a space in the Verovio editor. Does that address it?

**Comment by ahwitz** [comment] 2015-05-20 10:44
Because Ling-Xiao reported this, I wanted to make sure there wasn't a specific case he found that this happened in that is still unsolved.

**Closed** 2015-12-13 18:47 UTC
